### ISSUE TITLE
Problem to compile on Scientific Linux

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#26]
I am trying to compile on Scientific linux 6.1 with gcc 4.9.2, and I get the complains listed below.
I wonder wether the problem is related with the CombLayer code or the boost version I am using...

```
g++ -std=c++11 -c -g -fPIC -Wconversion -W -Wall -Wextra -Wno-comment -fexceptions -I../supportInc -I/opt/local/include \
               ./regexSupport.cxx

In file included from /usr/include/boost/regex/v4/regex.hpp:151:0,
                 from /usr/include/boost/regex.hpp:31,
                 from ./regexSupport.cxx:35:
/usr/include/boost/regex/v4/regex_iterator.hpp: In instantiation of ‘boost::regex_iterator<BidirectionalIterator, charT, traits>::regex_iterator(const boost::regex_iterator<BidirectionalIterator, charT, traits>&) [with BidirectionalIterator = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >; charT = char; traits = boost::regex_traits<char>]’:
/usr/include/boost/regex/v4/regex_iterator.hpp:150:34:   required from ‘boost::regex_iterator<BidirectionalIterator, charT, traits> boost::regex_iterator<BidirectionalIterator, charT, traits>::operator++(int) [with BidirectionalIterator = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >; charT = char; traits = boost::regex_traits<char>]’
./regexSupport.cxx:319:20:   required from here
/usr/include/boost/regex/v4/regex_iterator.hpp:121:25: error: use of deleted function ‘boost::shared_ptr<boost::regex_iterator_implementation<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >, char, boost::regex_traits<char> > >::shared_ptr(const boost::shared_ptr<boost::regex_iterator_implementation<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >, char, boost::regex_traits<char> > >&)’
       : pdata(that.pdata) {}
                         ^
In file included from /usr/include/boost/shared_ptr.hpp:17:0,
                 from /usr/include/boost/regex/v4/regex_workaround.hpp:43,
                 from /usr/include/boost/regex/v4/regex.hpp:32,
                 from /usr/include/boost/regex.hpp:31,
                 from ./regexSupport.cxx:35:
/usr/include/boost/smart_ptr/shared_ptr.hpp:168:25: note: ‘boost::shared_ptr<boost::regex_iterator_implementation<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >, char, boost::regex_traits<char> > >::shared_ptr(const boost::shared_ptr<boost::regex_iterator_implementation<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >, char, boost::regex_traits<char> > >&)’ is implicitly declared as deleted because ‘boost::shared_ptr<boost::regex_iterator_implementation<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >, char, boost::regex_traits<char> > >’ declares a move constructor or move assignment operator
 template<class T> class shared_ptr
                         ^
In file included from /usr/include/boost/regex/v4/regex.hpp:67:0,
                 from /usr/include/boost/regex.hpp:31,
                 from ./regexSupport.cxx:35:
/usr/include/boost/regex/v4/basic_regex.hpp: In instantiation of ‘boost::basic_regex<charT, traits>::basic_regex(const boost::basic_regex<charT, traits>&) [with charT = char; traits = boost::regex_traits<char>]’:
/usr/include/boost/regex/v4/regex_iterator.hpp:52:43:   required from ‘boost::regex_iterator_implementation<BidirectionalIterator, charT, traits>::regex_iterator_implementation(const regex_type*, BidirectionalIterator, boost::regex_constants::match_flag_type) [with BidirectionalIterator = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >; charT = char; traits = boost::regex_traits<char>; boost::regex_iterator_implementation<BidirectionalIterator, charT, traits>::regex_type = boost::basic_regex<char, boost::regex_traits<char> >; boost::regex_constants::match_flag_type = boost::regex_constants::_match_flags]’
/usr/include/boost/regex/v4/regex_iterator.hpp:113:46:   required from ‘boost::regex_iterator<BidirectionalIterator, charT, traits>::regex_iterator(BidirectionalIterator, BidirectionalIterator, const regex_type&, boost::regex_constants::match_flag_type) [with BidirectionalIterator = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >; charT = char; traits = boost::regex_traits<char>; boost::regex_iterator<BidirectionalIterator, charT, traits>::regex_type = boost::basic_regex<char, boost::regex_traits<char> >; boost::regex_constants::match_flag_type = boost::regex_constants::_match_flags]’
./regexSupport.cxx:79:55:   required from here
/usr/include/boost/regex/v4/basic_regex.hpp:390:29: error: use of deleted function ‘boost::shared_ptr<boost::re_detail::basic_regex_implementation<char, boost::regex_traits<char> > >::shared_ptr(const boost::shared_ptr<boost::re_detail::basic_regex_implementation<char, boost::regex_traits<char> > >&)’
       : m_pimpl(that.m_pimpl) {}
                             ^
In file included from /usr/include/boost/shared_ptr.hpp:17:0,
                 from /usr/include/boost/regex/v4/regex_workaround.hpp:43,
                 from /usr/include/boost/regex/v4/regex.hpp:32,
                 from /usr/include/boost/regex.hpp:31,
                 from ./regexSupport.cxx:35:
/usr/include/boost/smart_ptr/shared_ptr.hpp:168:25: note: ‘boost::shared_ptr<boost::re_detail::basic_regex_implementation<char, boost::regex_traits<char> > >::shared_ptr(const boost::shared_ptr<boost::re_detail::basic_regex_implementation<char, boost::regex_traits<char> > >&)’ is implicitly declared as deleted because ‘boost::shared_ptr<boost::re_detail::basic_regex_implementation<char, boost::regex_traits<char> > >’ declares a move constructor or move assignment operator
 template<class T> class shared_ptr
                         ^
In file included from /usr/include/boost/regex/v4/regex.hpp:67:0,
                 from /usr/include/boost/regex.hpp:31,
                 from ./regexSupport.cxx:35:
/usr/include/boost/regex/v4/basic_regex.hpp: In instantiation of ‘boost::shared_ptr<boost::re_detail::named_subexpressions_base<charT> > boost::re_detail::convert_to_named_subs(boost::shared_ptr<boost::re_detail::named_subexpressions<Other> >) [with To = char; From = char]’:
/usr/include/boost/regex/v4/perl_matcher_common.hpp:265:140:   required from ‘bool boost::re_detail::perl_matcher<BidiIterator, Allocator, traits>::find_imp() [with BidiIterator = const char*; Allocator = std::allocator<boost::sub_match<const char*> >; traits = boost::regex_traits<char>]’
/usr/include/boost/regex/v4/perl_matcher_common.hpp:230:20:   required from ‘bool boost::re_detail::perl_matcher<BidiIterator, Allocator, traits>::find() [with BidiIterator = const char*; Allocator = std::allocator<boost::sub_match<const char*> >; traits = boost::regex_traits<char>]’
/usr/include/boost/regex/v4/regex_search.hpp:56:24:   required from ‘bool boost::regex_search(BidiIterator, BidiIterator, boost::match_results<BidiIterator, Allocator>&, const boost::basic_regex<charT, traits>&, boost::regex_constants::match_flag_type, BidiIterator) [with BidiIterator = const char*; Allocator = std::allocator<boost::sub_match<const char*> >; charT = char; traits = boost::regex_traits<char>; boost::regex_constants::match_flag_type = boost::regex_constants::_match_flags]’
/usr/include/boost/regex/v4/regex_search.hpp:42:55:   required from ‘bool boost::regex_search(BidiIterator, BidiIterator, boost::match_results<BidiIterator, Allocator>&, const boost::basic_regex<charT, traits>&, boost::regex_constants::match_flag_type) [with BidiIterator = const char*; Allocator = std::allocator<boost::sub_match<const char*> >; charT = char; traits = boost::regex_traits<char>; boost::regex_constants::match_flag_type = boost::regex_constants::_match_flags]’
/usr/include/boost/regex/v4/regex_search.hpp:72:67:   required from ‘bool boost::regex_search(const charT*, boost::match_results<const charT*, Allocator>&, const boost::basic_regex<charT, traits2>&, boost::regex_constants::match_flag_type) [with charT = char; Allocator = std::allocator<boost::sub_match<const char*> >; traits = boost::regex_traits<char>; boost::regex_constants::match_flag_type = boost::regex_constants::_match_flags]’
./regexSupport.cxx:101:57:   required from here
/usr/include/boost/regex/v4/basic_regex.hpp:196:54: error: use of deleted function ‘boost::shared_ptr<boost::re_detail::named_subexpressions<char> >::shared_ptr(const boost::shared_ptr<boost::re_detail::named_subexpressions<char> >&)’
    return convert_to_named_subs_imp<To>(s, tag_type());
                                                      ^
In file included from /usr/include/boost/shared_ptr.hpp:17:0,
                 from /usr/include/boost/regex/v4/regex_workaround.hpp:43,
                 from /usr/include/boost/regex/v4/regex.hpp:32,
                 from /usr/include/boost/regex.hpp:31,
                 from ./regexSupport.cxx:35:
/usr/include/boost/smart_ptr/shared_ptr.hpp:168:25: note: ‘boost::shared_ptr<boost::re_detail::named_subexpressions<char> >::shared_ptr(const boost::shared_ptr<boost::re_detail::named_subexpressions<char> >&)’ is implicitly declared as deleted because ‘boost::shared_ptr<boost::re_detail::named_subexpressions<char> >’ declares a move constructor or move assignment operator
 template<class T> class shared_ptr
                         ^
In file included from /usr/include/boost/regex/v4/regex.hpp:67:0,
                 from /usr/include/boost/regex.hpp:31,
                 from ./regexSupport.cxx:35:
/usr/include/boost/regex/v4/basic_regex.hpp:178:58: error:   initializing argument 1 of ‘boost::shared_ptr<boost::re_detail::named_subexpressions_base<charT> > boost::re_detail::convert_to_named_subs_imp(boost::shared_ptr<boost::re_detail::named_subexpressions<To> >, const boost::integral_constant<bool, true>&) [with To = char]’
 inline boost::shared_ptr<named_subexpressions_base<To> > convert_to_named_subs_imp(
                                                          ^
In file included from /usr/include/boost/shared_ptr.hpp:17:0,
                 from /usr/include/boost/regex/v4/regex_workaround.hpp:43,
                 from /usr/include/boost/regex/v4/regex.hpp:32,
                 from /usr/include/boost/regex.hpp:31,
                 from ./regexSupport.cxx:35:
/usr/include/boost/smart_ptr/shared_ptr.hpp: In instantiation of ‘boost::shared_ptr< <template-parameter-1-1> >& boost::shared_ptr< <template-parameter-1-1> >::operator=(const boost::shared_ptr< <template-parameter-1-1> >&) [with T = boost::re_detail::named_subexpressions_base<char>]’:
/usr/include/boost/regex/v4/match_results.hpp:445:20:   required from ‘void boost::match_results<BidiIterator, Allocator>::set_named_subs(boost::shared_ptr<boost::re_detail::named_subexpressions_base<typename boost::re_detail::regex_iterator_traits<BidiIterator>::value_type> >) [with BidiIterator = const char*; Allocator = std::allocator<boost::sub_match<const char*> >; typename boost::re_detail::regex_iterator_traits<BidiIterator>::value_type = char]’
/usr/include/boost/regex/v4/perl_matcher_common.hpp:265:7:   required from ‘bool boost::re_detail::perl_matcher<BidiIterator, Allocator, traits>::find_imp() [with BidiIterator = const char*; Allocator = std::allocator<boost::sub_match<const char*> >; traits = boost::regex_traits<char>]’
/usr/include/boost/regex/v4/perl_matcher_common.hpp:230:20:   required from ‘bool boost::re_detail::perl_matcher<BidiIterator, Allocator, traits>::find() [with BidiIterator = const char*; Allocator = std::allocator<boost::sub_match<const char*> >; traits = boost::regex_traits<char>]’
/usr/include/boost/regex/v4/regex_search.hpp:56:24:   required from ‘bool boost::regex_search(BidiIterator, BidiIterator, boost::match_results<BidiIterator, Allocator>&, const boost::basic_regex<charT, traits>&, boost::regex_constants::match_flag_type, BidiIterator) [with BidiIterator = const char*; Allocator = std::allocator<boost::sub_match<const char*> >; charT = char; traits = boost::regex_traits<char>; boost::regex_constants::match_flag_type = boost::regex_constants::_match_flags]’
/usr/include/boost/regex/v4/regex_search.hpp:42:55:   required from ‘bool boost::regex_search(BidiIterator, BidiIterator, boost::match_results<BidiIterator, Allocator>&, const boost::basic_regex<charT, traits>&, boost::regex_constants::match_flag_type) [with BidiIterator = const char*; Allocator = std::allocator<boost::sub_match<const char*> >; charT = char; traits = boost::regex_traits<char>; boost::regex_constants::match_flag_type = boost::regex_constants::_match_flags]’
/usr/include/boost/regex/v4/regex_search.hpp:72:67:   required from ‘bool boost::regex_search(const charT*, boost::match_results<const charT*, Allocator>&, const boost::basic_regex<charT, traits2>&, boost::regex_constants::match_flag_type) [with charT = char; Allocator = std::allocator<boost::sub_match<const char*> >; traits = boost::regex_traits<char>; boost::regex_constants::match_flag_type = boost::regex_constants::_match_flags]’
./regexSupport.cxx:101:57:   required from here
/usr/include/boost/smart_ptr/shared_ptr.hpp:305:9: error: use of deleted function ‘boost::shared_ptr<boost::re_detail::named_subexpressions_base<char> >::shared_ptr(const boost::shared_ptr<boost::re_detail::named_subexpressions_base<char> >&)’
         this_type(r).swap(*this);
         ^
/usr/include/boost/smart_ptr/shared_ptr.hpp:168:25: note: ‘boost::shared_ptr<boost::re_detail::named_subexpressions_base<char> >::shared_ptr(const boost::shared_ptr<boost::re_detail::named_subexpressions_base<char> >&)’ is implicitly declared as deleted because ‘boost::shared_ptr<boost::re_detail::named_subexpressions_base<char> >’ declares a move constructor or move assignment operator
 template<class T> class shared_ptr
                         ^
make[1]: *** [regexSupport.o] Error 1
make: *** [libSupport] Error 2

```
